[phases.setup]
nixPkgs = ["python39", "postgresql", "gcc"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  ". /opt/venv/bin/activate",
  "flask db upgrade"
]

[start]
cmd = "gunicorn app:create_app() --bind 0.0.0.0:$PORT" 